FROM golang:1.25-alpine

WORKDIR /app

# Air for hot reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

CMD ["air", "-c", ".air.toml"]